## Academic and Research Roles

- **Graduate Student Researcher**, *University of California, Los Angeles*  
  *April 2024 – Present*  
  
- **Undergraduate Student Researcher**, *Xi'an Jiaotong-Liverpool University*  
  *July 2022 – August 2023*  



## Internships and Industry Work

**Clinical Trial Assistant**, *Suzhou Center for Disease Control and Prevention (CDC) Biobank*  
*August 2022 – September 2022*  

- Recorded data from an ongoing clinical trial on insulin efficacy and pH levels.  

- Analyzed the relationship between efficacy and pH using linear and logistic regression models.


**Audit Assistant**, *[KPMG Business Consulting Co., LTD. Suzhou Branch](https://kpmg.com/cn/zh/home.html)*  
*August 2021 – September 2021*  

- Processed related audit data  


**Business Center Assistant**, *[SOOCHOW Securities Co., LTD](https://tempwww.dwzq.com.cn)*  
*July 2020 – August 2020*  

- Conducted securities related business  



## Honors & Awards

- Statistics Graduate Scholars Award, *Rice University*, *2025*
- University Academic Achievement Award, *Xi'an Jiaotong-Liverpool University*, *2022*  
- University Academic Achievement Award, *Xi'an Jiaotong-Liverpool University*, *2021*
- University Academic Achievement Award, *Xi'an Jiaotong-Liverpool University*, *2020*
- Merit Student, *Xi'an Jiaotong-Liverpool University*, *2020*


